package br.com.creditcontract.adapter.in.rest.dto;

import br.com.creditcontract.domain.valueobject.MonetaryAmount;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

/** Current credit-contract representation returned by create and query APIs. */
@Schema(description = "Current state of one credit contract.")
public record CreditContractResponse(
		@Schema(description = "Contract identifier.", format = "uuid", example = "8f2d7c44-3a64-4de5-940a-80c6a4cf1f7a")
		String id,
		@Schema(description = "Human-facing number generated by PostgreSQL.", example = "CT-2026-000001")
		String contractNumber,
		@Schema(description = "Name captured in the immutable client snapshot.", example = "Maria Silva")
		String clientName,
		@Schema(description = "Current lifecycle state.", example = "ACTIVE",
				allowableValues = {"DRAFT", "UNDER_REVIEW", "APPROVED", "REJECTED", "ACCEPTED", "ACTIVE", "BLOCKED", "CANCELLED"})
		String status,
		@Schema(description = "Approved limit in Brazilian reais. Null before approval or when rejected.",
				example = "7500.00", nullable = true)
		String creditLimit,
		@Schema(description = "Contract creation time.", example = "2026-07-13T10:15:30")
		LocalDateTime createdAt,
		@Schema(description = "Optimistic-lock version incremented after persisted changes.", example = "4")
		Long version) {

	public static CreditContractResponse from(
			String id,
			String contractNumber,
			String clientName,
			String status,
			MonetaryAmount creditLimit,
			LocalDateTime createdAt,
			Long version) {
		return new CreditContractResponse(
				id,
				contractNumber,
				clientName,
				status,
				creditLimit == null ? null : creditLimit.amount().toPlainString(),
				createdAt,
				version);
	}
}
